export const CONFIG = {
  CONFERENCE_API_URL: import.meta.env.VITE_BASE_CONFERENCE_SERVICE_URL || "",
  IDENTITY_API_URL: import.meta.env.VITE_BASE_IDENTITY_SERVICE_URL || "",
  USERS_API_URL: import.meta.env.VITE_BASE_USERS_SERVICE_URL || "",
  ARTICLES_API_URL: import.meta.env.VITE_BASE_ARTICLES_SERVICE_URL || "",
  GOOGLE_CLIENT_ID: import.meta.env.VITE_GOOGLE_CLIENT_ID || "",

  DEFAULT_LANG: "en-US",
  MAX_IMAGE_SIZE: 1024 * 1024 * 10,
  MAX_3D_SIZE: 1024 * 1024 * 150,

  THREE_D: {
    MODEL_FOLDER_NAME: "MODEL",
    PREVIEWS_FOLDER_NAME: "PREVIEWS",
  },
};
